const SeoContent = () => (
  <section className="mt-8 sm:mt-12 lg:mt-16 max-w-4xl mx-auto w-full px-3 sm:px-5 lg:px-8 pb-10 sm:pb-16">
    <div className="bg-[#111118] border border-gray-800 rounded-2xl p-5 sm:p-8 md:p-10">
      <h2 className="text-2xl md:text-3xl font-bold text-white mb-5 tracking-tight">
        The Importance of Secure Passwords
      </h2>

      <p className="text-gray-400 leading-relaxed mb-5">
        In today's hyper-connected digital landscape, a strong password is your first and most
        critical line of defense against unauthorized access. Cybercriminals use sophisticated
        tools — including brute-force attacks, dictionary attacks, and credential-stuffing bots
        — that can crack a weak password in seconds. Yet despite widespread awareness, millions
        of people continue to use dangerously predictable passwords.
      </p>

      <h3 className="text-lg font-semibold text-cyan-300 mb-3 mt-6">
        What Makes a Password Weak?
      </h3>
      <ul className="list-disc list-inside text-gray-400 space-y-2 mb-5 leading-relaxed">
        <li>Short length — passwords under 8 characters are cracked almost instantly.</li>
        <li>Common words or phrases (e.g., <code className="text-emerald-400 font-mono text-sm">password</code>, <code className="text-emerald-400 font-mono text-sm">qwerty123</code>).</li>
        <li>Personal information such as birthdays, names, or pet names.</li>
        <li>Reusing the same password across multiple websites or services.</li>
        <li>Relying solely on lowercase letters with no numbers or special characters.</li>
      </ul>

      <h3 className="text-lg font-semibold text-cyan-300 mb-3 mt-6">
        Anatomy of a Strong Password
      </h3>
      <p className="text-gray-400 leading-relaxed mb-4">
        A truly secure password combines <span className="text-white font-medium">length</span>,{' '}
        <span className="text-white font-medium">complexity</span>, and{' '}
        <span className="text-white font-medium">randomness</span>. Security experts recommend:
      </p>
      <ul className="list-disc list-inside text-gray-400 space-y-2 mb-5 leading-relaxed">
        <li>A minimum of <strong className="text-white">16 characters</strong> — longer is always better.</li>
        <li>A mix of <strong className="text-white">uppercase and lowercase letters</strong>.</li>
        <li>At least one <strong className="text-white">number</strong> and one <strong className="text-white">special symbol</strong> (e.g., <code className="text-emerald-400 font-mono text-sm">!@#$%</code>).</li>
        <li>Completely <strong className="text-white">random</strong> — generated by a tool, not your imagination.</li>
        <li>Unique per account — <em>never</em> reused across sites.</li>
      </ul>

      <h3 className="text-lg font-semibold text-cyan-300 mb-3 mt-6">
        Best Practices for Password Safety
      </h3>
      <p className="text-gray-400 leading-relaxed mb-4">
        Generating a strong password is only half the battle. Follow these habits to stay
        protected long-term:
      </p>
      <ul className="list-disc list-inside text-gray-400 space-y-2 mb-5 leading-relaxed">
        <li>
          <strong className="text-white">Use a Password Manager</strong> — tools like Bitwarden, 1Password, or
          KeePass securely store all your credentials so you only need to remember one master password.
        </li>
        <li>
          <strong className="text-white">Enable Two-Factor Authentication (2FA)</strong> — adds an extra
          verification layer so a stolen password alone cannot grant access.
        </li>
        <li>
          <strong className="text-white">Rotate passwords regularly</strong> — especially after any
          suspected breach or when a service notifies you of a data leak.
        </li>
        <li>
          <strong className="text-white">Check breach databases</strong> — services like Have I Been Pwned
          let you verify whether your email or password appears in known data breaches.
        </li>
      </ul>

      <p className="text-gray-500 leading-relaxed text-sm border-t border-gray-800 pt-5 mt-6">
        Our password generator uses the browser's built-in{' '}
        <code className="text-emerald-400 font-mono">crypto.getRandomValues()</code> API —
        a cryptographically secure random number generator — ensuring that every password
        produced is truly unpredictable. No passwords are ever transmitted to or stored on any
        server. Your security is entirely local.
      </p>
    </div>
  </section>
)

export default SeoContent
